app v 1.0
AngryDogy/Task-manager pull request #1
Opened 2022-06-26 00:18 UTC by AngryDogy

2022-06-27 16:13 UTC, FrediKats commented
> Хотелось бы в идеале подключить ORM, хранить данные в sqllite и сделать web-view

Звучит как краткий обзор всей академии)

2022-06-27 16:18 UTC, FrediKats requested changes
Потерялись файлы .sln и .csproj. Ну и там ещё пару замечаний.

2022-06-27 16:18 UTC, FrediKats commented on Task.cs
> +    public Task(string name_, DateTime deadline_)
Можешь посмотреть пока кодстайл C#, на неймиг приватных полей и аргументов.

2022-06-27 16:18 UTC, FrediKats commented on Manager.cs
> +    }
А зачем тебе возвращать индекс из листа? Если тебе нужен доступ к созданной таске, то верни саму таску) В идеале, внешний мир не должен знать о том, что у тебя в листе хранится что-то.

2022-06-27 16:18 UTC, FrediKats commented on Manager.cs
> +            if (i == id)
Вложенность очень большая. Стоит подумать над упрощением.
id = индекс, кажется, что не очень идея т.к. оно может сломаться после удаления из центра.

2022-06-27 16:18 UTC, FrediKats commented on Client.cs
> +                            id = manager.add(words[1]);
Можно попробовать разделить на два класса логику парсинга аргументво и саму логику.

2022-06-30 20:55 UTC, AngryDogy commented on Manager.cs
> +    }
В данном случае я возвращаю скорее не индекс, а id, который был присвоен данному таску - мне нужна именно эта информация. В самом таске, к сожалению, не содержится инфа о id, под которым он хранится в manager'е, так что возвращать его не вариант

2022-06-30 20:58 UTC, AngryDogy commented on Manager.cs
> +            if (i == id)
id = индекс работает в моей программе, так как фактически я не удаляю task, а меняю его поле IsDeleted на true и далее его игнорирую. Так что это не ломает индексацию и id при удалении элемента из центра. 
Пару циклов ненужных нашел и убрал их

2022-06-30 20:59 UTC, AngryDogy commented on Client.cs
> +                            id = manager.add(words[1]);
Сделал

2022-06-30 20:59 UTC, AngryDogy commented on Task.cs
> +    public Task(string name_, DateTime deadline_)
Переименовал переменные согласно кодстайлу

2022-07-02 11:43 UTC, FrediKats approved these changes
Есть что переделывать, но мы это всё разберём на курсе.

2022-07-02 11:43 UTC, FrediKats commented on abstract_Manager.cs
> +abstract class Manager
Кажется, ты изобрёл интерфейс)

2022-07-02 17:39 UTC, merged